#!/bin/bash
# FILES: the location of cureutils' binaries
FILES=/home/plumaya/project/coreutils-8.28/src/*
for f in $FILES
do
    if [[ -x "$f" ]]
    then
        echo "Processing $f file..."
        # take action on each file. $f store current file name
        python3 preprocess.py $f
    fi
done
